my_proj/pybo/models.py
from pybo import db

class Question(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    subject = db.Column(db.String(200), nullable=False)
    content = db.Column(db.Text(), nullable=False)
    create_date = db.Column(db.DateTime(), nullable=False)

class Answer(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    question_id = db.Column(db.Integer, db.ForeignKey('question.id', ondelete='CASCADE'))
    question = db.relationship('Question', backref=db.backref('answer_set'))
    content = db.Column(db.Text(), nullable=False)
    create_date = db.Column(db.DateTime(), nullable=False)

my_proj/pybo/__init__.py
#__init__.py는 패키지를 만드는데 사용됨. 패키지를 import하면 자동으로 실행
from flask import Flask ,render_template
from flask_migrate import Migrate
from flask_sqlalchemy import SQLAlchemy

import os
import config #config가 인식이 안 되네 ^^.

db = SQLAlchemy()
migrate = Migrate()

def create_app():
    app = Flask(__name__)
    app.config.from_object(config)
    app.config['SQLALCHEMY_TRACK_MODIFICATIONS'] = False
    app.config['SECRET_KEY']= 'development' #Flask-WTF으로 form을 만드는데 CSRF 보안.
    BASE_DIR = os.path.dirname(__file__)
    SQLAlCHEMY_TRACK_MODIFICATIONS = False
    SQLAlCHEMY_DATABASE_URI = 'sqlite:///{}'.format(os.path.join(BASE_DIR,'pybo.db'))
    app.config['SQLALCHEMY_DATABASE_URI'] = SQLAlCHEMY_DATABASE_URI
    from . import models
    

    #ORM
    db.init_app(app)
    
    
    migrate.init_app(app, db)

    
    #import models, #현재 패키지에서 가져와야하므로?
    #.을 찍어야함.
    #blue print
    from .views import main_views, question_views, answer_views
    app.register_blueprint(main_views.bp)
    app.register_blueprint(question_views.bp)
    app.register_blueprint(answer_views.bp)
    
    return app

# @app.route('/', methods=['GET'])
# def index():
#     return "hello world"
# if __name__ == "__main__":
#     app.run(host="0.0.0.0",port=9000,debug=True)

my_proj/pybo/views/answer_views.py
from datetime import datetime

from flask import Blueprint, url_for, request, render_template
from werkzeug.utils import redirect

from pybo import db
from pybo.models import Question, Answer

from ..form import AnswerForm

bp = Blueprint('answer', __name__, url_prefix='/answer')

@bp.route('/create/<int:question_id>', methods=('POST',))#methods = ['POST', 'GET'])
def create(question_id):
    form = AnswerForm()
    question = Question.query.get_or_404(question_id)
    if form.validate_on_submit():
        content = request.form['content']
        answer = Answer(content=content, create_date=datetime.now())
        question.answer_set.append(answer)
        db.session.commit()
        return redirect(url_for('question.detail', question_id=question_id))
    return render_template('question/question_detail.html', question=question, form=form)

my_proj/pybo/views/main_views.py
from flask import Blueprint, render_template, url_for
# from pybo.models import Question
from werkzeug.utils import redirect

bp = Blueprint('main', __name__, url_prefix='/')

@bp.route('/hello')
def hello_pybo():
    return "hello world"

@bp.route('/')
def index():
    return redirect(url_for('question._list'))
# urlfor로 question으로 블루프린트 등록된 이름을 찾음. _list로 된 함수명, 
# question_view도 bp의 일환이니, 여기서 question이란 bq이름 찾아서 redirect

# @bp.route('/')
# def index():#sql asc ascending, desc descending
#     question_list = Question.query.order_by(Question.create_date.desc())
#     return render_template('question/question_list.html', question_list=question_list)
# @bp.route('/detail/<int:question_id>/')#매핑 규칙
# def detail(question_id):
#     question = Question.query.get_or_404(question_id)#get(question_id)
#     return render_template('question/question_detail.html', question=question)

my_proj/pybo/views/question_views.py
from flask import Blueprint, render_template, request, url_for
from datetime import datetime
from werkzeug.utils import redirect

from pybo.models import Question
from ..form import QuestionForm, AnswerForm

from .. import db


bp = Blueprint('question', __name__, url_prefix='/question')


@bp.route('/list/')
def _list():
    question_list = Question.query.order_by(Question.create_date.desc())
    return render_template('question/question_list.html', question_list=question_list)


@bp.route('/detail/<int:question_id>/')
def detail(question_id):
    form = AnswerForm()
    question = Question.query.get_or_404(question_id)
    return render_template('question/question_detail.html', question=question, form=form)
    # return render_template('question/question_detail.html', question=question) 


#GET 방식 요청이므로 그대로 질문 등록 화면을 보여 주고,
#<저장하기>는 POST 방식 요청이므로 데이터베이스에 질문 1건을 저장한 다음 질문 목록 화면으로 이동한다.
@bp.route('/create/',methods=['POST','GET'])
def create():
    form = QuestionForm()
    if request.method == 'POST' and form.validate_on_submit():
        question = Question(subject=form.subject.data, content=form.content.data, create_date=datetime.now())
        db.session.add(question)
        db.session.commit()
        return redirect(url_for('main.index'))
    return render_template('question/question_form.html', form= form)

my_proj/pybo/templates/base.html
<!doctype html>
<html lang="ko">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Bootstrap CSS  viewport는 모바일 설정인듯, 마치 미디어쿼리 느낌?-->
    <!--<link rel="stylesheet" href="{{ url_for('static', filename='bootstrap.min.css') }}">-->
    <!-- pybo CSS -->
    <link rel="stylesheet" href="{{ url_for('static', filename='style.css') }}">
    <title>Hello, pybo!</title>
</head>
<body>
<!-- 기본 템플릿 안에 삽입될 내용 Start -->
{% block content %}
{% endblock %}
<!-- 기본 템플릿 안에 삽입될 내용 End -->
</body>
</html>

my_proj/pybo/templates/question/question_detail.html
{% extends 'base.html' %}
{% block content %}

<h1>{{ question.subject }}</h1>

<div>
    {{ question.content }}
</div>

<h5>{{ question.answer_set|length }}개의 답변이 있습니다.</h5>
<div><!--|을 이용하여, filter answer_set중에 lenght-->
    <ul>
    {% for answer in question.answer_set %}
        <li>{{ answer.content }}</li>
    {% endfor %}
    </ul>
</div>

<form action="{{ url_for('answer.create', question_id=question.id) }}" method="post">
    {{ form.csrf_token }}
    <!-- 오류표시 Start -->
    {% for field, errors in form.errors.items() %}
    <div class="alert alert-danger" role="alert">
        <strong>{{ form[field].label }}</strong>: {{ ', '.join(errors) }}
    </div>
    {% endfor %}
    <!-- 오류표시 End -->

    <div class="form-group">
        <textarea name="content" id="content" rows="15"></textarea>
    </div>
    <input type="submit" value="답변등록">
</form>
{% endblock %}

my_proj/pybo/templates/question/question_form.html
{% extends 'base.html' %}
{% block content %}
<div class="container">
    <h5 class="my-3 border-bottom pb-2">질문등록</h5>
    <form method="post" class="post-form my-3">
        {{ form.csrf_token }}
        {% for field, errors in form.errors.items() %}
        <div class="alert alert-danger" role="alert">
            <strong>{{ form[field].label }}</strong>: {{ ', '.join(errors) }}
        </div>
        {% endfor %}
        <div class="form-group">
            <!--label tag, for id, input과 같이 쓰임. form에서-->
            <label for="subject">제목</label>
            <input type="text" class="form-control" name="subject" id="subject"
            value="{{ form.subject.data or '' }}">
            <input type="text" class="form-control" name="subject" id="subject">
        </div>
        <div class="form-group">
            <label for="content">내용</label>
            <textarea class="form-control" name="content"
            id="content" rows="10">{{ form.content.data or '' }}</textarea>
            <textarea class="form-control" name="content" id="content" rows="5"></textarea>
        </div>
        <button type="submit" class="btn btn-primary">저장하기</button>
<!--    {{ form.subject.label }}
        {{ form.subject() }}

        {{ form.content.label }}
        {{ form.content() }}

        <button type="submit" class="btn btn-primary">저장하기</button> -->
    </form>
</div>
{% endblock %}

my_proj/pybo/templates/question/question_list.html
{% extends 'base.html' %}
{% block content %}

    {% if question_list %}
    <ul>
    {% for question in question_list %}
        <li><a href="{{ url_for('question.detail', question_id=question.id) }}"">순서: {{ loop.index }} // {{ question.subject }}</a></li>
    {% endfor %}<!--뒤에 것은 parameter임. 원래는 detail/{{question_id}}-->
    </ul>
    <a href="{{ url_for('question.create') }}">질문 등록하기</a>
    {% else %}
    <p>질문이 없습니다.</p>
    {% endif %}

{% endblock %}